# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/1.0/include
obj-y   +=  gyroscope.o gyro_factory.o


obj-$(CONFIG_MTK_GYROHUB)      +=  gyrohub/
